version: '3.8'

services:
  bot:
    container_name: degen_bot
    build: .
    environment: 
      MONGODB_PREFIX: mongodb
      MONGODB_USERNAME: dev
      MONGODB_PASS: pass
      MONGODB_CLUSTER: mongo
    volumes:
      - .:/app

  mongo:
    container_name: degen_mongo
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./src/app/utils/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
volumes:
  mongodb: