name: Deploy to QA Environment
on:
    push:
        branches:
          - 'develop'
    pull_request:
        branches:
          - 'release/**'
jobs:
    deploy-qa:
        environment:
            name: preview
            url: url-logdna-here
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.10.0'
            - name: Install dependencies
              run: yarn install
            - name: Lint Code
              run: yarn lint
            - name: Build and Compile Typescript
              run: yarn build
            - name: Run test cases
              run: yarn test --watchAll=false
            - name: Deploy to Heroku Shared Test Environment
              uses: AkhileshNS/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.QA_HEROKU_API_KEY}}
                  heroku_app_name: 'heroku-app-name-here'
                  heroku_email: 'email-here'
                  procfile: 'worker: yarn qa'
              env:
                  HD_DISCORD_BOT_TOKEN: ${{secrets.QA_DISCORD_TOKEN}}
                  HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.QA_BOT_PUBLIC_KEY}}
                  HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.QA_BOT_APPLICATION_ID}}
                  HD_DISCORD_OWNER_ID: ${{secrets.QA_DISCORD_OWNER_ID}}
                  HD_MONGODB_USERNAME: ${{secrets.QA_MONGODB_USERNAME}}
                  HD_MONGODB_PASS: ${{secrets.QA_MONGODB_PASS}}
                  HD_MONGODB_CLUSTER: ${{secrets.QA_MONGODB_CLUSTER}}
                  HD_NOTION_TOKEN: ${{secrets.QA_NOTION_TOKEN}}
                  HD_LOGDNA_TOKEN: ${{secrets.QA_LOGDNA_TOKEN}}
            - name: Get current package version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.1.0
            - name: Sentry Release
              uses: getsentry/action-release@v1.1.6
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                environment: 'qa'
                version: 'project-name@${{ steps.package-version.outputs.current-version }}'
                sourcemaps: './dist'