name: Deploy to QA Environment
on:
    push:
        branches:
          - 'develop'
          - 'hotfix/**'
    pull_request:
        branches:
          - 'release/**'
jobs:
    deploy-qa:
        environment:
            name: preview
            url: https://app.logdna.com/273e532689/logs/view?apps=[app-name-here]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.10.0'
            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.1
              with:
                version: 6.x
            - name: Install dependencies
              run: pnpm install
            - name: Lint Code
              run: pnpm lint
            - name: Build and Compile Typescript
              run: pnpm build
            - name: Run test cases
              run: pnpm test
            - name: Deploy to Heroku Shared Test Environment
              uses: AkhileshNS/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.QA_HEROKU_API_KEY}}
                  heroku_app_name: 'heroku-app-name'
                  heroku_email: 'test@email.com'
                  procfile: 'worker: npm run start:qa'
              env:
                  HD_DISCORD_BOT_TOKEN: ${{secrets.QA_DISCORD_TOKEN}}
                  HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.QA_BOT_PUBLIC_KEY}}
                  HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.QA_BOT_APPLICATION_ID}}
                  HD_DISCORD_OWNER_ID: ${{secrets.QA_DISCORD_OWNER_ID}}
                  HD_MONGODB_USERNAME: ${{secrets.QA_MONGODB_USERNAME}}
                  HD_MONGODB_PASS: ${{secrets.QA_MONGODB_PASS}}
                  HD_MONGODB_CLUSTER: ${{secrets.QA_MONGODB_CLUSTER}}
                  HD_LOG_DNA_TOKEN: ${{secrets.QA_LOGDNA_TOKEN}}
                  HD_SENTRY_IO_DSN: ${{secrets.QA_SENTRY_IO_DSN}}
            - name: Get current package version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.1.0
            - name: Sentry Release
              uses: getsentry/action-release@v1.1.6
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                environment: 'qa'
                version: '[app-name]@${{ steps.package-version.outputs.current-version }}'
                sourcemaps: './dist'
