name: Deploy to Production Environment
on:
  push:
    branches:
      - 'main'
jobs:
  deploy-prod:
    environment:
      name: production
      url: url-logdna-here
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Run test cases
        run: yarn test --watchAll=false
      - name: Deploy to Heroku Shared Test Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
          heroku_app_name: 'heroku-app-name-here'
          heroku_email: 'emaul-here'
          procfile: 'worker: yarn prod'
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.PROD_DISCORD_TOKEN}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.PROD_BOT_PUBLIC_KEY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.PROD_BOT_APPLICATION_ID}}
          HD_DISCORD_OWNER_ID: ${{secrets.PROD_DISCORD_OWNER_ID}}
          HD_MONGODB_USERNAME: ${{secrets.PROD_MONGODB_USERNAME}}
          HD_MONGODB_PASS: ${{secrets.PROD_MONGODB_PASS}}
          HD_MONGODB_CLUSTER: ${{secrets.PROD_MONGODB_CLUSTER}}
          HD_NOTION_TOKEN: ${{secrets.PROD_NOTION_TOKEN}}
          HD_LOGDNA_TOKEN: ${{secrets.PROD_LOGDNA_TOKEN}}
          HD_SENTRY_IO_DSN: ${{secrets.PROD_SENTRY_IO_DSN}}
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          sourcemaps: './dist'
        with:
          environment: 'production'
          version: 'project-name@${{ steps.package-version.outputs.current-version }}'
          sourcemaps: './dist'